apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: eventhub-kafka-triggerauth
spec:
  secretTargetRef:
    - parameter: authMode
      name: app-credentials
      key: authMode
    - parameter: username
      name: app-credentials
      key: username
    - parameter: password
      name: app-credentials
      key: password
