apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: order-processor-scaledobject
  namespace: default
  labels:
    deploymentName: order-processor
spec:
  scaleTargetRef:
    deploymentName: order-processor
  pollingInterval: 15
  cooldownPeriod: 100
  maxReplicaCount: 10
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: <replace with eventhubs namespace>.servicebus.windows.net:9093
        consumerGroup: orders-app
        topic: <replace with event hubs topic name>
        lagThreshold: "10"
      authenticationRef:
        name: eventhub-kafka-triggerauth
